name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  BIN_NAME: gene-extract

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Rust

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: nightly

    - name: Cache cargo
      uses: Swatinem/rust-cache@v2

    - name: Build
      run: cargo +nightly build --verbose

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.BIN_NAME }}
        path: target/debug/${{ env.BIN_NAME }}

  format:
    runs-on: ubuntu-latest
    name: Format Rust
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
          components: rustfmt

      - name: Cache cargo
        uses: Swatinem/rust-cache@v2

      - name: Format
        run: cargo +nightly fmt --check
